name: Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # default is a pseudo 'merge' commit

      - name: Install tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install mvdan.cc/gofumpt@latest

      - name: gofmt
        run: diff <(gofmt -d . 2>/dev/null) <(printf '')

      - name: go vet
        run: go vet ./...

      - name: staticcheck
        run: staticcheck ./...

      - name: gofumpt
        run: diff <(gofumpt -d -e -l . 2>/dev/null) <(printf '')

      - name: go test
        run: go test -v ./...
